theme: jekyll-theme-cayman
title: "Grand: Finding Logic Bugs in Gremlin-Based Graph Database Systems via Randomized Differential Testing"
description:" Noted! This web is to show the bugs detected by Grand anonymously. Do not try to find the real information of the authors of Grand!"
